### ISSUE TITLE
WS Disconnected

### ISSUE THREAD

**Issue by AndersonatAMC** [nkaz001/collect-binancefutures#1]
Thank you for your wonderful application, I just found that after collecting several days, all websocket connections are dead. Is there any way to fix this? Thank you.

**Comment by nkaz001** [comment]
Sorry, I forgot to update it. This updated version will be okay. Run command is changed. Please see README.md

**Comment by AndersonatAMC** [comment]
Thank you so much, I'm testing, will update here if everything goes well. BTW, if I want to have data guaranteed to be complete, should I deploy multiple severs recoding same binance API?

**Comment by AndersonatAMC** [comment]
Also, are you interested in cooperation?

**Comment by nkaz001** [comment]
Having redundancies is the best. For your information, there is the secondary endpoint for Binance Futures stream. `wss://fstream-auth.binance.com` you need to authenticate and get `listenKey` using your API key. You can see a sample code at https://github.com/nkaz001/sample-trading-bot/tree/master/tradingbot
or please see Bianance's official API docs. https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams
But considering the cost of running multiple servers, it might be better to buy the data from data providers depending on the cost. https://tardis.dev is one of the data providers that I used to use. Currently, I don't consider cooperation, thanks for asking.
