### ISSUE TITLE
how to collect data under windows?

### ISSUE THREAD

**Issue by quant2008** [nkaz001/collect-binancefutures#2]
Under windows 10, I run python.exe collect/main.py  binancefutures btcusdt mnt/data,
and I got the folloing error. asyncio doesn't implement some function under windows.
I wonder how to collect data under windows?

![image](https://github.com/nkaz001/collect-binancefutures/assets/116711018/c320ed4e-67f5-4d7b-b5e5-512f102d1558)

**Comment by nkaz001** [comment]
I haven't thought about it running on Windows. If you use WSL or can setup WSL(Windows Subsystem for Linux), then try it on WSL?

**Comment by nkaz001** [comment]
Or just delete the line 536, that's about terminating the app when it receives SIGTERM. it has nothing to do with its core function.

**Comment by quant2008** [comment]
Thank you very much for your reply.
I deleted line 536 and ran again, got the following error. 


![image](https://github.com/nkaz001/collect-binancefutures/assets/116711018/015399b6-0f64-483c-a5b7-2d6a722673a6)

I am in China, I use a vpn proxy to access binancefutures.
I guess I need set proxy in aiohttp, but I don't know how. I tried set enviroment variable 
set http_proxy=http://127.0.0.1:7890
set https_proxy=http://127.0.0.1:7890
but doesn't work.

**Comment by nkaz001** [comment]
In that case, you need to set `proxy` parameter at `request` and `ws_connect` methods.

https://github.com/nkaz001/collect-binancefutures/blob/master/collect/binancefutures.py#L106
`response = await self.client.request(verb, url, timeout=timeout, proxy='http://127.0.0.1:7890')`

https://github.com/nkaz001/collect-binancefutures/blob/master/collect/binancefutures.py#L163
`async with session.ws_connect(url,  proxy='http://127.0.0.1:7890') as ws:`

Please see the following doc.

https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.ws_connect
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.request

For the best data quality(to reduce latency), I recommend you running at AWS Tokyo region if possible.
the result is significantly affected by latency, depending on the type of strategies used.

**Comment by quant2008** [comment]
It's very kind of you. It works now.

**Comment by quant2008** [comment]
Hello, I am downloading the data. The downloadded file btcusdt_20230730.dat is becoming bigger and bigger.
Now, it's 1.1G and it's still downloading. I wonder when will this download stop?

**Comment by nkaz001** [comment]
depending on trading volume day by day, but usually it's a few gb per day.
