### ISSUE TITLE
Unable to convert data, KeyError: 'T'

### ISSUE THREAD

**Issue by novis10813** [nkaz001/collect-binancefutures#9]
![image](https://github.com/nkaz001/collect-binancefutures/assets/81843268/30e7ec6d-4230-4cfe-83a0-9a81586554aa)

It seems that Binance change the format of their stream data?

![image](https://github.com/nkaz001/collect-binancefutures/assets/81843268/9cbc35cd-548c-4895-b6f5-64b81a4daf57)
from the above picture you can tell that the data from last year still got E and T as the key, but now it doesn't
Did I do something wrong or it just doesn't work anymore?

**Comment by nkaz001** [comment]
`T` still exists in the target streams. I think the message may not be for the trade or diff book stream. Could you check the raw message where the error occurs?

**Comment by novis10813** [comment]
![image](https://github.com/nkaz001/collect-binancefutures/assets/81843268/a4bed752-3fb2-4a9b-847c-044fce2a8776)

The error happened at row 183.
It is dealing with the first data stream without `data` as a dictionary key.

![image](https://github.com/nkaz001/collect-binancefutures/assets/81843268/4da7f3cd-e03c-4200-897e-f971b5b738a7)

And I checked the data. It seems that the `lastUpdateId` doesn't have `T` inside

**Comment by nkaz001** [comment]
Could you post the full message of the specific row? I checked the Binance API documentation, and nothing seems to have changed. It may be a temporary problem on Binance's side, but I'm unsure. Meanwhile, I think you can skip that message and rely on the natural refresh.

**Comment by novis10813** [comment]
I’ve checked the data I fetched recently. I found that every other event except `trade` has no `T` inside. And I also checked the Binance API documentation, and everything seems no problem there. I will try to figure it out in the future.

**Comment by nkaz001** [comment]
I think you may be connecting to the spot stream. In the spot stream, there is no `T` field in the diff depth stream. Therefore, it is inaccurate to use it, but, you have to use the `E` field instead. However, note that the `E` field represents the timestamp when the exchange sent the feed, not when the exchange actually accepted the order. Please refer to the documentation for more details. https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#diff-depth-stream

**Comment by novis10813** [comment]
This solve the problem, thanks!
